### ISSUE TITLE
How to get the BCNN_85 model?

### ISSUE THREAD

**Issue by doublemanyu** [CraneHzm/OxFlowers_BCNN#1]
HI
I run your code recently, but I can't find the model. Can you tell me how to train the model? Why can't I find the trained model in model_dir: Models/BCNN_85？

**Comment by zhenyangGao** [comment]
I can't find the mode,too. I try to uncomment the code but i don't find the code of saving model.Can you help me?Thank you very much!

**Comment by zhenyangGao** [comment]
> HI
> I run your code recently, but I can't find the model. Can you tell me how to train the model? Why can't I find the trained model in model_dir: Models/BCNN_85？

uncomment the code in main code. and give the value to loop.then to run.

**Comment by CraneHzm** [comment]
As I said in usage: "If the models do not exit, you can uncomment the training code in the main function to retrain the model." The model is very large, so I do not push it here. you can retrain the model to get the results.

**Comment by zhenyangGao** [comment]
Thank you very much,I have solved the problem.




------------------ 原始邮件 ------------------
发件人: "Jimmy Hu"<notifications@github.com>; 
发送时间: 2019年8月31日(星期六) 下午4:21
收件人: "CraneHzm/OxFlowers_BCNN"<OxFlowers_BCNN@noreply.github.com>; 
抄送: "流浪"<1923844529@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [CraneHzm/OxFlowers_BCNN] How to get the BCNN_85 model? (#1)




As I said in usage: "If the models do not exit, you can uncomment the training code in the main function to retrain the model." The model is very large, so I do not push it here. you can retrain the model to get the results.

**Comment by doublemanyu** [comment]
> 
> 
> As I said in usage: "If the models do not exit, you can uncomment the training code in the main function to retrain the model." The model is very large, so I do not push it here. you can retrain the model to get the results.

Thank you. I found it later and I forgot to release the question.

**Comment by zhenyangGao** [comment]
------------------ 原始邮件 ------------------
发件人: "doublemanyu"<notifications@github.com>; 
发送时间: 2019年8月31日(星期六) 下午5:34
收件人: "CraneHzm/OxFlowers_BCNN"<OxFlowers_BCNN@noreply.github.com>; 
抄送: "流浪"<1923844529@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [CraneHzm/OxFlowers_BCNN] How to get the BCNN_85 model? (#1)



 
As I said in usage: "If the models do not exit, you can uncomment the training code in the main function to retrain the model." The model is very large, so I do not push it here. you can retrain the model to get the results.
  
Thank you. I found it later and I forgot to release the question.
